const char* web_ui_html = 
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"    <meta charset='UTF-8'>"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"    <title>MUS4 配网设置</title>"
"    <style>"
"        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f0f2f5; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }"
"        .container { background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); width: 100%; max-width: 400px; }"
"        h2 { text-align: center; color: #333; margin-bottom: 20px; }"
"        .form-group { margin-bottom: 15px; }"
"        label { display: block; margin-bottom: 5px; color: #666; font-weight: bold; }"
"        input[type='text'], input[type='password'] { width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box; font-size: 16px; }"
"        button { width: 100%; padding: 12px; background-color: #007bff; color: white; border: none; border-radius: 5px; font-size: 16px; font-weight: bold; cursor: pointer; transition: background-color 0.3s; }"
"        button:hover { background-color: #0056b3; }"
"        .status { margin-top: 20px; padding: 15px; border-radius: 5px; text-align: center; font-weight: bold; display: none; }"
"        .status.loading { display: block; background-color: #fff3cd; color: #856404; }"
"        .status.success { display: block; background-color: #d4edda; color: #155724; }"
"        .status.error { display: block; background-color: #f8d7da; color: #721c24; }"
"    </style>"
"</head>"
"<body>"
"    <div class='container'>"
"        <h2>MUS4 智能配网设置</h2>"
"        <div class='form-group'>"
"            <label for='ssid'>WiFi 名称 (SSID)</label>"
"            <input type='text' id='ssid' value='newhome_iot' placeholder='请输入WiFi名称'>"
"        </div>"
"        <div class='form-group'>"
"            <label for='pwd'>WiFi 密码</label>"
"            <input type='password' id='pwd' value='wxl922922' placeholder='请输入WiFi密码'>"
"        </div>"
"        <button onclick='submitConfig()'>提交配置</button>"
"        <div id='statusMsg' class='status'>等待操作...</div>"
"    </div>"
""
"    <script>"
"        function setStatus(type, msg) {"
"            const statusEl = document.getElementById('statusMsg');"
"            statusEl.className = 'status ' + type;"
"            statusEl.innerText = msg;"
"        }"
""
"        function submitConfig() {"
"            const ssid = document.getElementById('ssid').value;"
"            const pwd = document.getElementById('pwd').value;"
"            if (!ssid || !pwd) { alert('SSID和密码不能为空!'); return; }"
"            "
"            setStatus('loading', '正在下发配置给Linux主机，请稍候...');"
"            "
"            fetch('/api/provision', {"
"                method: 'POST',"
"                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },"
"                body: 'ssid=' + encodeURIComponent(ssid) + '&pwd=' + encodeURIComponent(pwd)"
"            }).then(res => res.text()).then(data => {"
"                if (data === 'OK') {"
"                    pollStatus();"
"                } else {"
"                    setStatus('error', '下发配置失败');"
"                }"
"            }).catch(err => setStatus('error', '网络请求异常'));"
"        }"
""
"        function pollStatus() {"
"            let attempts = 0;"
"            const maxAttempts = 30; // 30秒超时"
"            const timer = setInterval(() => {"
"                attempts++;"
"                fetch('/api/status').then(res => res.text()).then(state => {"
"                    if (state.startsWith('OK|')) {"
"                        clearInterval(timer);"
"                        setStatus('success', '配网成功！IP地址: ' + state.split('|')[1]);"
"                    } else if (state.startsWith('FAIL|')) {"
"                        clearInterval(timer);"
"                        setStatus('error', '配网失败: ' + state.split('|')[1]);"
"                    } else {"
"                        setStatus('loading', 'Linux主机正在连接路由器 (' + attempts + 's)...');"
"                    }"
"                });"
"                if (attempts >= maxAttempts) {"
"                    clearInterval(timer);"
"                    setStatus('error', '配网超时 (30s)，请检查密码是否正确');"
"                }"
"            }, 1000);"
"        }"
"    </script>"
"</body>"
"</html>";
