#pragma once

#define MUS4_FIRMWARE_NAME "MUS4"
#define MUS4_FIRMWARE_VERSION "v1.8.24"
#define MUS4_BUILD_DATE __DATE__
#define MUS4_BUILD_TIME __TIME__
#define MUS4_BUILD_INFO MUS4_FIRMWARE_NAME " " MUS4_FIRMWARE_VERSION " " MUS4_BUILD_DATE " " MUS4_BUILD_TIME
